language: csharp
solution: BluzelleNEO.sln
sudo: required
mono: latest
dotnet: 2.0.0
install:
  - unzip Build/avm_compiler.zip -d $TRAVIS_BUILD_DIR/
script:
  - dotnet restore
  - dotnet build
  - neon $TRAVIS_BUILD_DIR/Bluzelle.NEO.Contract/bin/Debug/netcoreapp2.0/BluzelleContract.dll -nodebug
  - dotnet test