language: csharp
solution: BluzelleNEO.sln
sudo: required
mono: latest
dotnet: 2.0.0
install:
  - unzip Build/avm_compiler.zip -d $TRAVIS_BUILD_DIR/
  - echo '#!/bin/sh' > neon
  - echo 'mono neon.exe "$@" >> neon
  - ls
  - export PATH="$TRAVIS_BUILD_DIR/NEO/;$PATH"    
script:
  - dotnet restore
  - dotnet build
  - dotnet test