language: csharp
solution: BluzelleNEO.sln
sudo: required
mono: latest
dotnet: 2.0.0
install:
  - unzip Build/avm_compiler.zip -d $TRAVIS_BUILD_DIR/
  - cp Build/mono mono
  - ls
script:
  - dotnet restore
  - dotnet build
  - dotnet test